cask_args appdir: "/Applications"

# brew
brew "asdf"
brew "awscli"
brew "bat"
brew "curl"
brew "gh"
brew "ghq"
brew "gnu-sed"
brew "gnupg"
brew "golang-migrate"
brew "grep"
brew "fzf"
brew "jq"
brew "just"
brew "libpq"
brew "pinentry-mac"
brew "sheldon"
brew "starship"
brew "tmux"
brew "tree"
brew "trivy"
brew "actionlint"
brew "mycli"
brew "pgcli"
brew "pinact"
brew "duckdb"
brew "tflint"
brew "packer"
brew "graphviz"
brew "azure-cli"
brew "terminal-notifier"
brew "cloudflare-wrangler"
brew "joachimbrindeau/ccusage-monitor/ccusage-monitor"

# tap
tap "homebrew/cask-fonts" # font
tap "hashicorp/tap" # hashicorp
tap "joachimbrindeau/ccusage-monitor" # claude code usage menu bar

# cask
cask "alfred"
cask "docker-desktop"
cask "iina"
cask "notion"
cask "appcleaner"
cask "dropbox"
cask "iterm2"
cask "bettertouchtool"
cask "stats"
cask "cyberduck"
cask "gcloud-cli"
cask "keepassxc"
cask "visual-studio-code"
cask "slack"
cask "figma"
cask "drawio"
cask "chatgpt"
cask "atok"
cask "claude"
cask "claude-code"
cask "pgadmin4"

# font
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "font-hack-nerd-font"
