cask_args appdir: "/Applications"

# brew
brew "ansible"
brew "asdf"
brew "awscli"
brew "aws-vault"
brew "circleci"
brew "curl"
brew "gh"
brew "ghq"
brew "gnu-sed"
brew "gnupg"
brew "golang-migrate"
brew "grep"
brew "hub"
brew "jq"
brew "just"
brew "libpq"
brew "peco"
brew "pinentry-mac"
brew "pwgen"
brew "python@3.9"
brew "sheldon"
brew "starship"
brew "tmux"
brew "tree"
brew "trivy"
brew "actionlint"
brew "mycli"

# font
brew "font-hackgen"
brew "font-hackgen-nerd"
brew "font-hack-nerd-font

# tap
tap "homebrew/cask-fonts" # font

# cask
cask "alfred"
cask "docker"
cask "iina"
cask "notion"
cask "appcleaner"
cask "dropbox"
cask "iterm2"
cask "raspberry-pi-imager"
cask "bettertouchtool"
cask "google-chrome"
cask "jetbrains-toolbox"
cask "stats"
cask "cyberduck"
cask "google-cloud-sdk"
cask "keepassx"
cask "visual-studio-code"
cask "slack"
cask "figma"