# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

# https://sheldon.cli.rs/Examples.html#deferred-loading-of-plugins-in-zsh
[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins]

# PATH configuration
[plugins.path-setup]
inline = 'export PATH="/opt/homebrew/opt/libpq/bin:/opt/homebrew/bin/:$PATH"'

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
[plugins.brew-completion]
inline = 'type brew &>/dev/null && FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"'

# [plugins.rust-zsh-completions]
# github = "ryutok/rust-zsh-completions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.compinit]
inline = "autoload -Uz compinit && compinit -u && zsh-defer compinit && zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'"
