add_newline = true 
command_timeout = 1000 
scan_timeout = 30 # timeout for file scan

# プロンプトの表示順序
format = """
$username\
$directory\
$git_branch\
$git_status\
$aws\
$gcloud\
$docker_context\
$nodejs\
$python\
$rust\
$golang\
$cmd_duration\
$line_break\
$character"""

[character]
error_symbol = "[x](bold red)"
success_symbol = "[>](bold green)"
vimcmd_symbol = "[<](bold green)"

[directory]
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[cmd_duration]
format = "took [$duration]($style) " 
min_time = 2000 # 2秒以上で表示

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "️🇦️ "

[aws.region_aliases]
ap-northeast-1 = "jp"

[gcloud]
format = '[$symbol$active]($style) '
style = 'bold yellow'
symbol = '️🇬️ '

[docker_context]
format = "via [🐋 $context](blue bold)"

[nodejs]
format = "via [$symbol($version )]($style)"
symbol = " "

[python]
format = "via [$symbol($version )]($style)"
symbol = " "

[rust]
format = "via [$symbol($version )]($style)"
symbol = " "

[golang]
format = "via [$symbol($version )]($style)"
symbol = " "

[username]
disabled = false
format = "[$user 🌱]($style) "
show_always = true
style_root = "black bold"
style_user = "white bold"
